/// <autosync enabled="true" />
/// <reference path="bootstrap.min.js" />
/// <reference path="jquery.validate.js" />
/// <reference path="jquery.validate.unobtrusive.js" />
/// <reference path="jquery-2.2.1.js" />
/// <reference path="jquery-2.2.1.min.js" />
/// <reference path="knockout-3.4.0.js" />
/// <reference path="modernizr-2.6.2.js" />
/// <reference path="respond.js" />
///<reference path="typings/jquery/jquery.d.ts" />
///<reference path="typings/knockout/knockout.d.ts" />
